apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-parcelize'

def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

android {
    compileSdkVersion 34
    buildToolsVersion '34.0.0'

    namespace "cn.archko.mupdf"

    ndkVersion "25.2.9519653"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }

    signingConfigs {
        release {
            v1SigningEnabled true
            v2SigningEnabled true
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }

    defaultConfig {
        applicationId 'cn.archko.mupdf'
        minSdkVersion 21
        targetSdkVersion 33
        versionCode 15
        versionName "1.2"
        vectorDrawables {
            useSupportLibrary true
        }
        signingConfig signingConfigs.release

        ndk.abiFilters 'arm64-v8a'
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.release
            minifyEnabled false
            jniDebuggable true
            //proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation('androidx.appcompat:appcompat:1.6.1')
    api "androidx.multidex:multidex:2.0.1"
    //api 'androidx.recyclerview:recyclerview:1.3.2'
    api "androidx.constraintlayout:constraintlayout:2.1.4"

    api "androidx.fragment:fragment:.1.6.2"
    api "androidx.fragment:fragment-ktx:1.6.2"

    api project(':reader')
    api project(':pdf-recyclerview')
}