apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-parcelize'

android {
    compileSdkVersion 34
    buildToolsVersion '34.0.0'

    namespace "cn.archko.pdf"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 21
        versionCode 1
        versionName "1.0"
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }

    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    lintOptions { abortOnError false }
}
dependencies {
    api fileTree(include: ['*.jar'], dir: 'libs')
    api "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"

    api "androidx.vectordrawable:vectordrawable:1.2.0"
    api "androidx.viewpager2:viewpager2:1.1.0"
    api "androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.3"

    api "com.google.android.material:material:1.12.0"

    api project(":readercommon")
    api project(":pdf-recyclerview")
    api project(":vudroid")
}